name: Set MIME types

on:
  push:
    branches:
      - master

jobs:
  set_mime_types:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set MIME types
        run: |
          echo ".css text/css" > ./.github/mime.types
          echo ".js text/javascript" >> ./.github/mime.types

      - name: Commit changes
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add ./.github/mime.types
          git commit -m "Set MIME types for GitHub Pages"
          git push
